In [21]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
import numpy as np

In [22]:
# Sample documents
documents = [
    "I love natural language processing",
    "I love machine learning",
    "Natural language processing is interesting",
    "Machine learning is powerful"
]

In [23]:
def bag_of_words(documents):
    vectorizer = CountVectorizer()

    bow_matrix = vectorizer.fit_transform(documents)

    print("BAG OF WORDS")
    print("-" * 50)

    print("Features:")
    print(vectorizer.get_feature_names_out())

    print("\nBoW Matrix:")
    print(bow_matrix.toarray())

In [24]:
def tf_idf(documents):
    vectorizer = TfidfVectorizer()

    tfidf_matrix = vectorizer.fit_transform(documents)

    print("\nTF-IDF")
    print("-" * 50)

    print("Features:")
    print(vectorizer.get_feature_names_out())

    print("\nTF-IDF Matrix:")
    print(np.round(tfidf_matrix.toarray(), 2))

In [25]:
bag_of_words(documents)


BAG OF WORDS
--------------------------------------------------
Features:
['interesting' 'is' 'language' 'learning' 'love' 'machine' 'natural'
 'powerful' 'processing']

BoW Matrix:
[[0 0 1 0 1 0 1 0 1]
 [0 0 0 1 1 1 0 0 0]
 [1 1 1 0 0 0 1 0 1]
 [0 1 0 1 0 1 0 1 0]]


In [26]:
tf_idf(documents)


TF-IDF
--------------------------------------------------
Features:
['interesting' 'is' 'language' 'learning' 'love' 'machine' 'natural'
 'powerful' 'processing']

TF-IDF Matrix:
[[0.   0.   0.5  0.   0.5  0.   0.5  0.   0.5 ]
 [0.   0.   0.   0.58 0.58 0.58 0.   0.   0.  ]
 [0.54 0.42 0.42 0.   0.   0.   0.42 0.   0.42]
 [0.   0.47 0.   0.47 0.   0.47 0.   0.59 0.  ]]
